### ISSUE TITLE
Problem loading XML - CannotResolveClassException: kg.apc.jmeter.vizualizers.CorrectedResultCollector

### ISSUE THREAD

**Issue by rabestro** [anboralabs/intellij-jmeter#2]
```text
java.lang.IllegalArgumentException: Problem loading XML from:'/Users/jegors/Projects/performance-tests/jmeter-files/tests2/ProcessingTypeTest.jmx'. 
Cause:
CannotResolveClassException: kg.apc.jmeter.vizualizers.CorrectedResultCollector

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/kg.apc.jmeter.vizualizers.CorrectedResultCollector
line number         : 348
version             : not available
-------------------------------
```

**Comment by dalgarins** [comment]
@rabestro kg.apc.jmeter.vizualizers.CorrectedResultCollector is a custom plugin? or something installed or created by you?

**Comment by rabestro** [comment]
> @rabestro kg.apc.jmeter.vizualizers.CorrectedResultCollector is a custom plugin? or something installed or created by you?

It was one of the custom plugins from https://jmeter-plugins.org/
The error was even if I disable the component (listener) in the test plan.

**Comment by dalgarins** [comment]
@rabestro can you share your jmeter file? or maybe another file using that plugin.

**Comment by rabestro** [comment]
[Sample.txt](https://github.com/anboralabs/intellij-jmeter/files/12067603/Sample.txt)

**Comment by kcwhite** [comment]
Same here, except with a different plugin, UltimateThreadGroup. I asked GPT how to resolve it:

> To resolve the error, you'll need to install the JMeter Plugins Manager, which will then allow you to easily install the "Ultimate Thread Group" plugin, as well as other plugins.
> Here are the general steps to do this:
> 
> Download the JMeter Plugins Manager JAR file from the JMeter Plugins website. You can find the JAR file here: https://jmeter-plugins.org/wiki/PluginsManager/
> 
> Once downloaded, put the JAR file into the "lib/ext" directory of your JMeter installation.
> Restart JMeter. You should now see a "Plugins Manager" option in the "Options" menu.
> In the Plugins Manager, you can install the "Ultimate Thread Group" plugin (and any others that you need).
> After the plugin is installed, you should be able to open your test plan without encountering the error.

**Comment by dalgarins** [comment]
@rabestro, I almost fix the issue, I added the jmeter plugin manager to my plugin. this is the result.

<img width="1383" alt="Screenshot 2023-12-03 at 12 34 19 PM" src="https://github.com/anboralabs/intellij-jmeter/assets/8527174/3b7ef335-f22d-4eef-9966-85207ad904ab">

**Comment by dalgarins** [comment]
@rabestro next version: 1.2.3 will have the jmeter plugin repository
