### ISSUE TITLE
JMeter viewer does not support ParameterizedController

### ISSUE THREAD

**Issue by andychao2017** [anboralabs/intellij-jmeter#20]
java.lang.IllegalArgumentException: Problem loading XML from:'C:\Users\xxx\xxx\xxx.jmx'. 
Cause:
CannotResolveClassException: kg.apc.jmeter.control.ParameterizedController

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree[6]/kg.apc.jmeter.control.ParameterizedController
line number         : 4558
version             : not available
-------------------------------

**Comment by dalgarins** [comment]
@andychao2017 kg.apc.jmeter.control.ParameterizedController is a custom plugin? if the answer is yes, please install the plugin with the JMeter repository inside the plugin, you could find the repository in tools, JMeter plugin repository.

**Comment by dalgarins** [comment]
@andychao2017 try version: 1.4.0 I will close this issue.
